management:
  info:
    defaults:
      enabled: false
    env:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,beans,env
      base-path: /my-actuator
    jmx:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
      show-components: always
    info:
      enabled: true
    beans:
      enabled: true
    env:
      enabled: true
      additional-keys-to-sanitize: java.*,sun.*
  server:
    port: 8081
    base-path: /management
info:
  hello: HelloWorld
  welcome: Welcome to the world of Spring.
  app:
    encoding: @project.build.sourceEncoding@
    source: @java.version@
    target: @java.version@
