management:
  server:
    base-path: /management
    port: 8081
  endpoints:
    web:
      base-path: /my-actuator
      exposure:
        include: health,env,info,beans,shop,metrics,prometheus,shutdown
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    env:
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: true
  metrics:
    distribution:
      percentiles:
        order.summary: 0.95
    tags:
      region: cn-shanghai-1
server:
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s