spring:
  datasource:
    url: jdbc:mysql://localhost/binary-tea?useUnicode=true&characterEncoding=utf8
    username: binary-tea
    password: binary-tea
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
